# TODO
# 2. get download link from .info file
# 3. verify MD5 sum
# 4. test 32-bit if applicable
# 5. catch and register failures smartly
FROM vbatts/slackware:14.2
WORKDIR /slackbuilds/minikube
COPY minikube/. .
RUN wget https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-linux-amd64 --no-check-certificate
RUN md5sum minikube-linux-amd64 > md5sum.txt
RUN chmod +x minikube.SlackBuild && ./minikube.SlackBuild
RUN installpkg /tmp/minikube*.tgz
RUN cat md5sum.txt
ENTRYPOINT [ "minikube", "version" ]
