# TODO
# 2. get download link from .info file
# 3. verify MD5 sum
# 4. test 32-bit if applicable
# 5. catch and register failures smartly
FROM vbatts/slackware:14.2
WORKDIR /slackbuilds/jenv
COPY jenv/. .
RUN wget https://github.com/jenv/jenv/archive/0.5.4.tar.gz --no-check-certificate
RUN chmod +x jenv.SlackBuild && ./jenv.SlackBuild
RUN installpkg /tmp/jenv*.tgz
RUN md5sum 0.5.4.tar.gz
ENTRYPOINT [ "jenv", "commands" ]
