# TODO
# 2. get download link from .info file
# 3. verify MD5 sum
# 4. test 32-bit if applicable
# 5. catch and register failures smartly
FROM vbatts/slackware:14.2
WORKDIR /slackbuilds/cf-cli
COPY cf-cli/. .
RUN wget https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.51.0/cf-cli_6.51.0_linux_x86-64.tgz --no-check-certificate
RUN chmod +x cf-cli.SlackBuild && ./cf-cli.SlackBuild
RUN installpkg /tmp/cf-cli*.tgz
ENTRYPOINT [ "cf", "version" ]
