# TODO
# 2. get download link from .info file
# 3. verify MD5 sum
# 4. test 32-bit if applicable
# 5. catch and register failures smartly
FROM vbatts/slackware:14.2
WORKDIR /slackbuilds/cf-cli
COPY cf-cli/. .
RUN wget https://s3-us-west-1.amazonaws.com/v7-cf-cli-releases/releases/v7.1.0/cf7-cli_7.1.0_linux_x86-64.tgz --no-check-certificate
RUN md5sum cf7-cli_7.1.0_linux_x86-64.tgz
RUN chmod +x cf-cli.SlackBuild && ./cf-cli.SlackBuild
RUN installpkg /tmp/cf-cli*.tgz
ENTRYPOINT [ "cf", "version" ]
