# TODO
# 2. get download link from .info file
# 3. verify MD5 sum
# 4. test 32-bit if applicable
# 5. catch and register failures smartly
FROM vbatts/slackware:14.2
WORKDIR /slackbuilds/crystal-lang
COPY crystal-lang/. .
RUN wget https://github.com/crystal-lang/crystal/releases/download/0.34.0/crystal-0.34.0-1-linux-x86_64.tar.gz --no-check-certificate
RUN chmod +x crystal-lang.SlackBuild && ./crystal-lang.SlackBuild
RUN installpkg /tmp/crystal-lang*.tgz
ENTRYPOINT [ "crystal", "--version" ]
