# TODO
# 2. get download link from .info file
# 3. verify MD5 sum
# 4. test 32-bit if applicable
# 5. catch and register failures smartly
FROM vbatts/slackware:14.2
WORKDIR /slackbuilds/octant
COPY octant/. .
RUN wget https://github.com/vmware-tanzu/octant/releases/download/v0.16.3/octant_0.16.3_Linux-64bit.tar.gz --no-check-certificate
RUN chmod +x octant.SlackBuild && ./octant.SlackBuild
RUN installpkg /tmp/octant*.tgz
RUN md5sum octant_0.16.3_Linux-64bit.tar.gz
ENTRYPOINT [ "octant", "version" ]
