# TODO
# 2. get download link from .info file
# 3. verify MD5 sum
# 4. test 32-bit if applicable
# 5. catch and register failures smartly
FROM vbatts/slackware:14.2
WORKDIR /slackbuilds/fly
COPY fly/. .
RUN wget https://github.com/concourse/concourse/releases/download/v6.7.4/fly-6.7.4-linux-amd64.tgz --no-check-certificate
RUN chmod +x fly.SlackBuild && ./fly.SlackBuild
RUN installpkg /tmp/fly*.tgz
RUN md5sum fly-6.7.4-linux-amd64.tgz
ENTRYPOINT [ "fly", "--version" ]
